version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./back-end:/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Configuración para MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: